[commit_types]
  behavior = "append"

  [[commit_types.types]]
    tag = "BUILD"
    description = "Changes that affect the build system or external dependencies (e.g., gulp, broccli, npm)"
    bg_block = "#4a3422"
    fg_block = "#ecc7a3"
    bg_msg = "#2a1c10"
    fg_msg = "#d3aa84"

[commit_format]
  type_format = ""

[release_config]
  version = "v0.3.1"
  repository = "Cerebellum-ITM/Echo"
  binary_assets_path = "bin/"
  auto_build = true
  build_tool = "make"
  build_target = "build_release"
